### ISSUE TITLE
Too many redirects when user changes password

### ISSUE THREAD

**Issue by jamie-biddulph** [dualcube/moodle-theme_rocket#1]
On a 3.1.5 Moodle site using rocket theme 2.7 (Build: 20140823) (2014091804)

When a user is forced to change their password by going to /login/change_password.php this triggers a POST followed by upwards of 20 GET requests within the same second, giving a browser error of "The page isn't redirecting properly" in Firefox or "<sitename> redirected you too many times." in Chrome.

On the same Moodle site with clean theme, this functionality works fine.

**Comment by parthajeet** [comment]
Hello,

Can you create a user checking the force password change and provide us the user details.We have to check the issue in your site as we didn't faced such issue.

Regards,
Parthajeet~

**Comment by satacm** [comment]
The problem seems to be the line "require_login()" in the ./theme/rocket/layout/default.php file.
(Version: 2014091804. Release: 2.7 (Build: 20140823)

Comment out the "require_login();"  line, and forgot_password.php will work.
I'm not sure why this line is there. If you have forgotten your password, login is NOT required.
Is there another reason why this is there. (Will this commenting out break the reason it was included?)

regards,
martin

**Comment by parthajeet** [comment]
Hello,

We have updated the plugin you can download the latest update from github or moodle.org .

Regards,
Parthajeet~

**Comment by satacm** [comment]
default1.php was added to the distribution
But default.php still remains. 
The theme will still be broken.

**Comment by parthajeet** [comment]
The 'base' layout which is for forgot_password.php has been changed default1.php.

Please let us know if you find any broken instance.

Regards,
Parthajeet~
